version: "3"

services:
  web:
    container_name: mynode
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
        - mongo
  mongo:
    container_name: mymogno
    image: mongo
    ports:
      - "27017:27017"